### ISSUE TITLE
feature request: batch mode

### ISSUE THREAD

**Issue by zh99998** [diosney/node-iproute#1]
iproute2 has a "-b" param that can accept multi commands at a time, like this
https://github.com/ashi009/bestroutetb/issues/11
it's really useful when executing thousands of iproute2 commands.

**Comment by diosney** [comment]
Sure! I will look into it and let you know.

**Comment by diosney** [comment]
BTW If you can contribute a PR will be more than welcome :smile:

**Comment by zh99998** [comment]
closing this since long time inactive

**Comment by diosney** [comment]
Sorry, was very busy in other projects...

I will reopen this, since I plan to refresh this project anytime soon, please, keep it that one until a PR is contributed by me or anyone else :D

**Comment by diosney** [comment]
Done in v2.0.0-beta.3.

I surely took my time on this, sorry 🥲 , life is richer than we expect.

See API docs:

https://diosney.github.io/node-iproute/modules/batch.html

Examples: 
https://github.com/diosney/node-iproute/blob/master/EXAMPLES.md#ip--batch-batch-mode-support--man-page
